/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pricning.serv.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Modelos service. Represents a row in the &quot;PRINCING_Modelos&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.pricning.serv.model.impl.ModelosModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.pricning.serv.model.impl.ModelosImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Modelos
 * @generated
 */
@ProviderType
public interface ModelosModel extends BaseModel<Modelos> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a modelos model instance should use the {@link Modelos} interface instead.
	 */

	/**
	 * Returns the primary key of this modelos.
	 *
	 * @return the primary key of this modelos
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this modelos.
	 *
	 * @param primaryKey the primary key of this modelos
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this modelos.
	 *
	 * @return the uuid of this modelos
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this modelos.
	 *
	 * @param uuid the uuid of this modelos
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this modelos.
	 *
	 * @return the ID of this modelos
	 */
	public long getId();

	/**
	 * Sets the ID of this modelos.
	 *
	 * @param id the ID of this modelos
	 */
	public void setId(long id);

	/**
	 * Returns the modelo name of this modelos.
	 *
	 * @return the modelo name of this modelos
	 */
	@AutoEscape
	public String getModeloName();

	/**
	 * Sets the modelo name of this modelos.
	 *
	 * @param modeloName the modelo name of this modelos
	 */
	public void setModeloName(String modeloName);

}