/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pricning.serv.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Pricing service. Represents a row in the &quot;PRINCING_Pricing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.pricning.serv.model.impl.PricingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.pricning.serv.model.impl.PricingImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Pricing
 * @generated
 */
@ProviderType
public interface PricingModel extends BaseModel<Pricing> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pricing model instance should use the {@link Pricing} interface instead.
	 */

	/**
	 * Returns the primary key of this pricing.
	 *
	 * @return the primary key of this pricing
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pricing.
	 *
	 * @param primaryKey the primary key of this pricing
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this pricing.
	 *
	 * @return the uuid of this pricing
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this pricing.
	 *
	 * @param uuid the uuid of this pricing
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this pricing.
	 *
	 * @return the ID of this pricing
	 */
	public long getId();

	/**
	 * Sets the ID of this pricing.
	 *
	 * @param id the ID of this pricing
	 */
	public void setId(long id);

	/**
	 * Returns the first name of this pricing.
	 *
	 * @return the first name of this pricing
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this pricing.
	 *
	 * @param firstName the first name of this pricing
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this pricing.
	 *
	 * @return the last name of this pricing
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this pricing.
	 *
	 * @param lastName the last name of this pricing
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the car model of this pricing.
	 *
	 * @return the car model of this pricing
	 */
	@AutoEscape
	public String getCarModel();

	/**
	 * Sets the car model of this pricing.
	 *
	 * @param carModel the car model of this pricing
	 */
	public void setCarModel(String carModel);

	/**
	 * Returns the identity document of this pricing.
	 *
	 * @return the identity document of this pricing
	 */
	@AutoEscape
	public String getIdentityDocument();

	/**
	 * Sets the identity document of this pricing.
	 *
	 * @param identityDocument the identity document of this pricing
	 */
	public void setIdentityDocument(String identityDocument);

	/**
	 * Returns the sucursal of this pricing.
	 *
	 * @return the sucursal of this pricing
	 */
	@AutoEscape
	public String getSucursal();

	/**
	 * Sets the sucursal of this pricing.
	 *
	 * @param sucursal the sucursal of this pricing
	 */
	public void setSucursal(String sucursal);

	/**
	 * Returns the department of this pricing.
	 *
	 * @return the department of this pricing
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this pricing.
	 *
	 * @param department the department of this pricing
	 */
	public void setDepartment(String department);

	/**
	 * Returns the province of this pricing.
	 *
	 * @return the province of this pricing
	 */
	@AutoEscape
	public String getProvince();

	/**
	 * Sets the province of this pricing.
	 *
	 * @param province the province of this pricing
	 */
	public void setProvince(String province);

	/**
	 * Returns the product type of this pricing.
	 *
	 * @return the product type of this pricing
	 */
	@AutoEscape
	public String getProductType();

	/**
	 * Sets the product type of this pricing.
	 *
	 * @param productType the product type of this pricing
	 */
	public void setProductType(String productType);

	/**
	 * Returns the product model of this pricing.
	 *
	 * @return the product model of this pricing
	 */
	@AutoEscape
	public String getProductModel();

	/**
	 * Sets the product model of this pricing.
	 *
	 * @param productModel the product model of this pricing
	 */
	public void setProductModel(String productModel);

	/**
	 * Returns the prodcut version of this pricing.
	 *
	 * @return the prodcut version of this pricing
	 */
	@AutoEscape
	public String getProdcutVersion();

	/**
	 * Sets the prodcut version of this pricing.
	 *
	 * @param prodcutVersion the prodcut version of this pricing
	 */
	public void setProdcutVersion(String prodcutVersion);

	/**
	 * Returns the contact channel of this pricing.
	 *
	 * @return the contact channel of this pricing
	 */
	@AutoEscape
	public String getContactChannel();

	/**
	 * Sets the contact channel of this pricing.
	 *
	 * @param contactChannel the contact channel of this pricing
	 */
	public void setContactChannel(String contactChannel);

	/**
	 * Returns the phone of this pricing.
	 *
	 * @return the phone of this pricing
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this pricing.
	 *
	 * @param phone the phone of this pricing
	 */
	public void setPhone(String phone);

	/**
	 * Returns the client type of this pricing.
	 *
	 * @return the client type of this pricing
	 */
	@AutoEscape
	public String getClientType();

	/**
	 * Sets the client type of this pricing.
	 *
	 * @param clientType the client type of this pricing
	 */
	public void setClientType(String clientType);

}